name: Build Android APK

on:
  push:
    tags:
      - 'v*'

jobs:
  build-android:
    runs-on: ubuntu-latest  # Usa Ubuntu para compatibilidade com Android builds
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Flet and dependencies
        run: |
          pip install flet
          pip install -r requirements.txt

      - name: Build Android APK
        run: |
          flet build apk
          mkdir release_assets
          mv build/apk/app-release.apk release_assets/
          ls -la release_assets/

      - name: Upload APK to Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          files: release_assets/app-release.apk
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_REPO_ACTION  }}  # Usa o token padrão do GitHub
